version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: lufthansa-mongodb
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017

  fastapi:
    build: 
      context: .
      dockerfile: ./api/Dockerfile
    command: ["sh", "-c", "mlflow server --backend-store-uri ./api/mlruns --default-artifact-root ./api/mlruns --host 0.0.0.0 --port 5000 & uvicorn api.fastapi_main:app --host 0.0.0.0 --port 8000"]
    container_name: fastapi-app
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://admin:password@mongodb:27017/
    ports:
      - 8000:8000
      - 5000:5000
    volumes:
      - .:/app

volumes:
  mongodb-data:
